kind: Secret
apiVersion: v1
metadata:
  name: minio-secret
stringData:
  minio_root_user: {{ .Values.minio_root_user}}
  minio_root_password: minio_1_2_3


apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: minio-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: minio-secret
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: secret/data/hub/minio-secret
