apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: openai-keys
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: openai-keys
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: secret/data/hub/openai-keys
